# General params for training
num_learning_steps: 40000
num_rollout_steps: 100
learning_rate_val: 0.00025

# Configuration params for the active damping environment

time_interval: 0.1
wave_speed: 1.0
system_length: 2.0
num_lattice_points: 20

# Parameters of the warmup force
drive_magnitude: 2.0

# How many steps to apply a fixed random impulse to start vibrating the bridge
num_warmup_steps: 20
# How many steps to allow the the bridge to equilibriate after warmup
num_equi_steps: 20




timepoints_per_step: 1
max_steps: 1000

# How many pistons, will spread uniformly on bridge interior
num_force_points: 3
# Force width is in units of the system length
force_width: 0.05
min_force: -1.0
max_force: 1.0
min_u: -20
max_u: 20






